MODULE_TOPDIR = ../..

PGM = r.futures.pga

LIBES = $(SEGMENTLIB) $(RASTERLIB) $(GISLIB) $(MATHLIB)
DEPENDENCIES = $(SEGMENTDEP) $(RASTERDEP) $(GISDEP)

include $(MODULE_TOPDIR)/include/Make/Module.make

default: cmd
